require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.nvim_lspconfig"
require "user.telescope"
require "user.treesitter"
require("user.lualine")
--require "user.terminal"
require "user.keymaps"
--require "user.bclose"
require "user.fidget"
